FROM nvidia/cuda:12.2.2-cudnn8-devel-ubuntu20.04

WORKDIR /workspace

# Install necessary packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    curl \
    git \
    wget \
    vim \
    gcc \
    openssl \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3.11 ipykernel python-graphviz \
    && conda update conda \
    && conda clean --all --yes

# Install VSCode
RUN curl -fsSL https://code-server.dev/install.sh | sh

RUN code-server --install-extension ms-python.python && \
    code-server --install-extension ms-toolsai.jupyter

RUN echo "root:root" | chpasswd

### Create SSL certificate (For HTTPS)
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/cert.key \
    -out /etc/ssl/certs/cert.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=localhost"

RUN mkdir -p ~/.config/code-server && \
    echo "password: root" > ~/.config/code-server/config.yaml && \
    echo "bind-addr: 0.0.0.0:8080" >> ~/.config/code-server/config.yaml && \
    echo "cert: /etc/ssl/certs/cert.crt" >> ~/.config/code-server/config.yaml && \
    echo "cert-key: /etc/ssl/private/cert.key" >> ~/.config/code-server/config.yaml

EXPOSE 8080

RUN rm -rf /workspace/*

CMD code-server --bind-addr 0.0.0.0:8080 .