version: "3.9"

services:
  tensorflow:
    image: keras-mlflow:latest
    build:
      context: .
    container_name: tensorflow_gpu
    command: python "/workspace/mlflow/Keras Deeplearning/keas_dl_validation.py"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - "D:/Sagi_JJU D/MlFlow:/workspace"
    working_dir: /workspace