version: '3.9'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.0.0
    container_name: mlflow
    ports:
      - "5110:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlruns
    volumes:
      - /var/services/homes/juya1021/Juhyung/Docker/Mlflow:/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0

# volumes:
#  mlflow_data: