version: '3.8'

services:
  vscode-torch:
    image: juhyung1021/vscode-torch:latest
    container_name: vscode-torch
    ports:
      - "18094:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    tty: true
    restart: always