FROM juhyung1021/condadocker-base

WORKDIR /workspace

# Install necessary packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    curl \
    wget \
    vim \
    gcc \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3.11 ipykernel python-graphviz \
    && conda update conda \
    && conda clean --all --yes

COPY . .
RUN pip install -r dockerfile-requirements-python.txt \
    && pip install --upgrade jupyter_client

# Install VSCode
RUN curl -fsSL https://code-server.dev/install.sh | sh
# RUN code-server --install-extension ms-python.python
RUN code-server --install-extension ms-python.python \
 && code-server --install-extension ms-toolsai.jupyter


RUN echo "root:root" | chpasswd

RUN mkdir -p ~/.config/code-server && \
    echo "password: root" > ~/.config/code-server/config.yaml && \
    sed -i 's|password:.*|password: root|g' ~/.config/code-server/config.yaml

EXPOSE 8080

CMD code-server --bind-addr 0.0.0.0:8080 .