FROM tensorflow/tensorflow:2.14.0-gpu

RUN pip install --upgrade pip && \
    pip install --ignore-installed \
                pandas \
                scikit-learn \
                mlflow==2.10.2 
RUN pip install seaborn